version: "3"

services:
  dev:
    container_name: pointcept-dev
    hostname: pointcept-dev
    image: pedrosidra0/pointcept:v4.1
    entrypoint: "./docker-entrypoint.sh"
    command: "bash"
    working_dir: /workspaces/Pointcept
    network_mode: host
    environment: 
      - TERM=xterm-256color
      # - SLURM_NODEID 
      # - DIST_URL 
      # - WORLD_SIZE 
      # - MASTER_PORT 
      # - MASTER_ADDR
    # ports:
    #   - "23450:23450"
    #   - "23451:23451"
    #   - "23452:23452"
    #   - "23453:23453"
    #   - "23454:23454"
    #   - "23455:23455"
    #   - "23456:23456"

    volumes:
      - .:/workspaces/Pointcept
      - $HOME/.netrc:/root/.netrc
    shm_size: "32gb"
    privileged: false
    stdin_open: true # docker run -i
    tty: true # docker run -t
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
